

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    `maven-publish`
    id("io.qameta.allure") version "2.11.2"
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.org.seleniumhq.selenium.selenium.java)
    testImplementation(libs.junit.junit)
    testImplementation(libs.io.github.bonigarcia.webdrivermanager)
    testImplementation(libs.org.assertj.assertj.core)
    testImplementation(libs.io.cucumber.cucumber.junit)
    testImplementation(libs.io.cucumber.cucumber.java)
    testImplementation("io.qameta.allure:allure-junit5:2.24.0")
    testImplementation("io.qameta.allure:allure-commandline:2.24.0")
    testImplementation("io.qameta.allure:allure-assertj:2.24.0")
    testImplementation("io.qameta.allure:allure-rest-assured:2.24.0")
    testImplementation("io.qameta.allure:allure-java-commons:2.24.0")

    testImplementation("org.aspectj:aspectjweaver:1.9.5")


}

group = "ru.karpov"
version = "1.0-SNAPSHOT"
description = "BSBPTest"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}